### ISSUE TITLE
[Priest][Disc] Atonement

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#6997] opened 2016-09-30 12:19 UTC
**Describe the issue you're having**:
The spells hwat should aply atonement dont aplay them.

**Explain how you expect it work**:
Plea, Power Word: Shield, Shadow Mend, and Power Word: Radiance also apply Atonement to your target for 15 sec.
When you deal spell damage, you instantly heal all targets affected by Atonement for 40.1% of the damage done.

And at the moment the bugged atonement health the enemys what ur attacking. 
Example if i hit an enemy with pennance i heal them for the 30% of each domg of pennance 3tiks ->3x30% of dmg ammount healed.
and this is with all damage spells.

**Steps to reproduce the problem**:

1. relogged
2. respecced
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=81749/atonement

**Comment by Redrian-Valhalla** [comment] 2016-09-30 13:10
Duplicate of https://github.com/Valhalla-Gaming/Tracker/issues/6621

**Closed by Redrian-Valhalla** 2016-09-30 13:10 UTC
