### ISSUE TITLE
Buying bank slots doesn't expand your bank

### ISSUE THREAD

**Issue by braebrook** [Valhalla-Gaming/Tracker#8809] opened 2017-02-10 16:43 UTC
**Describe the issue you're having**:
I"ve purchased two bank slots and equipped bags in those slots and the amount of storage in my bank does not get larger, it stays the same that you are given at the beginning.  It's not recognizing that I have equipped more bags in my bank to expand storage.

**Explain how you expect it work**:
The amount of storage in your bank should expand to reflect the number of bank slots with equipped bags.

**Steps to reproduce the problem**:

1.   Bought bag from auction house
2.   Purchases bank slot in stormwind
3.   Amount of storage stayed the same

**Links to Wowhead, YouTube, etc**:
![image](https://cloud.githubusercontent.com/assets/24441178/22835263/1058b826-ef86-11e6-8cb1-a16e418420c9.png)

**Comment by Lebiedz** [comment] 2017-02-10 17:45
For me it's working fine, you just have to close all your visible bags (default hotkey: B) and reopen them. You can also just click on the additional bags in the bank.

**Comment by braebrook** [comment] 2017-02-10 17:55
Actually I do see that in my most recent screen shot it is working but not really how it is intended or in the retail version of the game.  In my most recent screen shot I see the two lighter gray bags pop up for my bank, but in retail your actual teller window expands and shows more spots, so that is what I was saying wasn't working but if it's not supposed to do that on this realm that is ok.

![image](https://cloud.githubusercontent.com/assets/24441178/22837786/20b6a84a-ef90-11e6-97b4-aa7e46a7a588.png)

**Comment by narodigg** [comment] 2017-02-10 19:45
Last I played retail (an older expansion)  this is how the bank worked.  Is it possible that your interpretation of retail expanding the teller bank slots was an addon that combined your bank bags with the default bank window space?  I believe I had an addon that did that for me.   At any rate closing this for now as working as intended.

**Closed by narodigg** 2017-02-10 19:45 UTC
