### ISSUE TITLE
Holy Paladin Talents Auras Dissapearing

### ISSUE THREAD

**Issue by Haeratus** [Valhalla-Gaming/Tracker#7671] opened 2016-11-14 19:51 UTC
Aura of Mercy, Aura of Sacrifice and Devotion Aura are disapearing when you are teleported to any battle grounds.

http://www.wowhead.com/spell=183415/aura-of-mercy
http://www.wowhead.com/spell=183416/aura-of-sacrifice
http://www.wowhead.com/spell=183425/devotion-aura

**Comment by Moustachos** [comment] 2016-11-15 08:48
Unless you're experiencing a different issue, here is the intended behavior of these auras.

As the caster (paladin): the auras are indeed removed on teleport but they are added back once you enter the new map (ie: the battleground).

As a party member: the auras are removed when the caster (paladin) leaves your map or is out range (or logs out), the auras will be added back once you either:
- enter the battleground with the caster (paladin)
- get in range again
- wait for the paladin to login

Tell me in which case you are and if you're experiencing a different issue, because I haven't been able to reproduce this issue under any other circumstances.

**Comment by Haeratus** [comment] 2016-11-15 14:23
I will test now and type it here.

**Comment by Haeratus** [comment] 2016-11-15 14:59
Just tested it all (remember that these Auras are Passive Talents):

The Auras are being removed and added back when you (the caster):
-Have the Aura on and teleport to Dalaran, Stormwind, any other place in Azeroth.

The Auras are being removed and NOT being added back when you (the caster):
-Have the Aura on and get teleported to a Battle Ground (possibly arenas too).
-Have the Aura on and Logout from the game.

**Comment by Moustachos** [comment] 2016-11-15 16:05
> The Auras are being removed and NOT being added back when you (the caster):
-Have the Aura on and get teleported to a Battle Ground (possibly arenas too).
-Have the Aura on and Logout from the game.

Can't reproduce your issue in these conditions, the aura is still here after teleporting to a BG / logout on my character.

**Comment by Haeratus** [comment] 2016-11-15 23:17
I will try to contact other holy paladins ingame, but if the problem is just on me, what am I supose to do? I just followed the guide strictly in the valhalla site and the updates that came before where working for me, like the Divine Steed spell update.

**Comment by Haeratus** [comment] 2016-11-16 10:45
I contacted the following players: Ananke, Ressurection, holly pally, they are all holy paladins and they can confirm this bug.

**Comment by Moustachos** [comment] 2017-02-28 09:14
Fixed in a previous update.

**Closed by Moustachos** 2017-02-28 09:14 UTC
Labels: Class-Paladin, Type-Spell
