### ISSUE TITLE
(Quest/Spell) The Kessel Run

### ISSUE THREAD

**Issue by Aedomus** [Valhalla-Gaming/Tracker#600] opened 2015-05-24 22:00 UTC
Objective; Kessel at Kessel's Crossing wants you to warn High Chief Stillpine at Stillpine Hold, Exarch Menelaous at Azure Watch and Admiral Odesyus at Odesyus' Landing of the imminent blood elf invasion. Return to Kessel when you complete this task. You have 15 minutes. (Be sure to keep it out of water.)

Issue; Upon accepting the quest, I was able to obtain the Elekk spell and ride the Elekk...but as I exited the Bloodmyst Isle area into Azuremyst Isle and taking the left path to warn the first NPC on my list (High Chief Stillpine)...the Elekk spell disappears at coordinates (Azuremyst Isle 48.7. 12.0)

http://www.wowhead.com/quest=9663/the-kessel-run

**Comment by Kelpo122** [comment] 2015-05-24 22:06
Also, that quest can't be compleeted since you dont have a dialog option to warn those NPC's at their gossips.

**Comment by Aedomus** [comment] 2015-05-24 22:10
Thanks...I just found that out. Plus to test the spell further...I was able to take the right path and the Elekk spell had no issues...so there is an issue when taking the left path.

**Comment by Kelpo122** [comment] 2015-05-24 22:49
Since the flightpath in exodar doesn't work I used the elekk from that quest to get a ride to exodar when i needed to get back from bloodmyst

**Comment by Aedomus** [comment] 2015-05-24 23:05
That's a great idea : )

**Comment by Malae1** [comment] 2015-06-14 23:28
Quest is completable, however dismount still happens. No timer countdown.

**Comment by Guybrush-Hellscream** [comment] 2015-08-31 10:45
The quest is fine but the problem is similare to the Dun Morogh's issue (#2079).
A portion of that road is considered to be in the cave below it.
I'll open a new issue for that cave thing so we can close this one.

**Comment by Pure-Valhalla** [comment] 2016-02-14 21:16
Quest works as intended.

**Closed by Pure-Valhalla** 2016-02-14 21:16 UTC
Labels: Priority-Normal, Type-Quest, Type-Spell
