### ISSUE TITLE
Lava Lash Damage

### ISSUE THREAD

**Issue by Orunla** [Valhalla-Gaming/Tracker#5658] opened 2016-06-23 21:51 UTC
I'm playing an **orc enhancement shaman** which is **lvl 18** right now.
I noticed my **lava lash** to display and deal way **more dmg with weak offhand weapons** (both dps and flat dmg) than with stronger weapons, which is horrible.

When using a tomahawk (2-5 dmg, 2.06dps) in offhand lava lash tooltip says 121 dmg.
When using Giant Tarantula fang (5-10 dmg, 4.17 dps) in offhand tooltip says 93 dmg.
The spell is supposed to scale with offhand weapon dmg.

The spell also deals way more dmg with the tomahawk than with the dagger allthough both dps and flat dmg are higher on the latter. Just feels bad.

**While testing the above issue out I also noticed my general dps in character screen to be very faulty.**

When equipped with a dagger in mainhand that has flat 4-8 dmg with 3.75 dps (1,6 speed) my "Damage" says 25-28
However when equipped with a club that has 3-7 dmg with 2.27 dps (2.2 speed) the "Damage" says 31-35.
Tested with various weapons.

**Comment by nuhrii** [comment] 2016-06-27 04:57
Lava lash is working as intended, close this. Lava lash is a unique spell that has a special modifier for its damage calculations, it will do more damage based on how slow your weapon is. When I tested with a dagger that has a much faster attack speed the damage is low, when tested with a axe that has a much slower attack speed the damage goes up. This is how the spell and the class as a whole was intended, to use much slower weapons, like axes and maces, not faster weapons, like daggers.

**Comment by Tregeta** [comment] 2016-06-27 20:13
Thanks for the confirmation nuhrii, will close this then.

**Closed by Tregeta** 2016-06-27 20:13 UTC
Labels: Class-Shaman, Priority-High
