### ISSUE TITLE
Holy Paladin Talent Auras Disapearing

### ISSUE THREAD

**Issue by Haeratus** [Valhalla-Gaming/Tracker#7637] opened 2016-11-13 22:14 UTC
Holy Paladin Talent Auras disapear when you log out.

They should not disapear.

http://www.wowhead.com/spell=183425/devotion-aura
http://www.wowhead.com/spell=183415/aura-of-mercy
http://www.wowhead.com/spell=183416/aura-of-sacrifice

**Comment by Moustachos** [comment] 2016-11-15 08:49
Unless you're experiencing a different issue, here is the intended behavior of these auras.

As the caster (paladin): the auras are indeed removed on teleport but they are added back once you enter the new map (ie: the battleground).

As a party member: the auras are removed when the caster (paladin) leaves your map or is out range (or logs out), the auras will be added back once you either:
- enter the battleground with the caster (paladin)
- get in range again
- wait for the paladin to login

Tell me in which case you are and if you're experiencing a different issue, because I haven't been able to reproduce this issue under any other circumstances.

**Comment by Moustachos** [comment] 2017-02-28 09:14
Fixed in a previous update.

**Closed by Moustachos** 2017-02-28 09:14 UTC
Labels: Class-Paladin
