### ISSUE TITLE
Warlock talent: mana tap

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6490] opened 2016-09-10 15:47 UTC
**Describe the issue you're having**:
mana tap is not consuming any mana
**Explain how you expect it work**:
mana tap is suppose to comsume 25% of your current mana to give you a buff for 20s that increases damage by 10%
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=196104/mana-tap

**Comment by nuhrii** [comment] 2016-09-10 23:30
close this its a duplicate of #6302

**Closed** 2016-09-14 12:38 UTC

**Comment by Moustachos** [comment] 2016-12-03 20:00
Ref #5979
