### ISSUE TITLE
[Hunter] BUG CALL PET 1 SPELL

### ISSUE THREAD

**Issue by kirinaism** [Valhalla-Gaming/Tracker#3186] opened 2015-10-25 01:34 UTC
http://www.wowhead.com/spell=883/call-pet-1

Whenever my hunter tries to call her pet, it doesnt appear. I created a hunter and after logged out and log in again, my pet disappeared and I can't call it anymore.

**Comment by Malae1** [comment] 2015-10-25 02:14
What race were you? What pet was in your slot 1 that you were trying to summon? What is your in-game character name?

**Comment by kirinaism** [comment] 2015-10-26 02:27
I am a Undead hunter, it was the first pet... A spider. In this case, when I made the character, I was able to see the spider icon everytime I tried to cast the spell. But after logout and login again, the same icon disappeared and I wasn't be able to call the pet anymore. My character name is Morgani.

**Comment by Moustachos** [comment] 2016-05-12 16:20
Can't reproduce this bug, looks like a character-specific issue.

Closing it, please contact a GM.

**Comment by Moustachos** [comment] 2016-05-12 16:21
Ref #2266

**Closed by Moustachos** 2016-05-12 16:20 UTC
Labels: Class-Hunter, Type-Pet, Type-Spell
