### ISSUE TITLE
[Arms - Warrior] Trauma

### ISSUE THREAD

**Issue by assassin14** [Valhalla-Gaming/Tracker#7041] opened 2016-10-05 11:02 UTC
**Describe the issue you're having**:
Does not Add bleed damage when using Slam and Whirlwind and may not add accumulate increased damage
**Explain how you expect it work**:
Should be able to add bleed damage on slam and whirlwind
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment] 2016-10-05 12:46
duplicate of https://github.com/Valhalla-Gaming/Tracker/issues/6928
please check for existing reports.

**Closed by Redrian-Valhalla** 2016-10-05 12:46 UTC
