### ISSUE TITLE
warlock talent: demonic circle

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6493] opened 2016-09-10 16:12 UTC
**Describe the issue you're having**:demonic circle can be placed but are unable to teleport to it.

**Explain how you expect it work**:
after the demonic circle is placed the skill is suppose to change to the demonic circle teleport spell.

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=48020/demonic-circle

**Comment by nuhrii** [comment] 2016-09-10 23:37
duplicate of #1346

**Closed** 2016-12-03 19:58 UTC

**Comment by Moustachos** [comment] 2016-12-03 20:00
Ref #5979
