### ISSUE TITLE
Warlock talent: burning rush

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6492] opened 2016-09-10 15:57 UTC
**Describe the issue you're having**: after activating burning rush the spell can not be canceled unleash you mount up or change instances.

**Explain how you expect it work**:after activating burning rush the skill should change to a cancel button to turn off burning rush.

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=111400/burning-rush

**Comment by nuhrii** [comment] 2016-09-10 23:34
duplicate of #1060

**Comment by llamalama** [comment] 2016-10-09 13:45
This spell should also auto cancel if you don't have enough hp but it is instead killing you.

**Closed** 2016-12-03 19:58 UTC

**Comment by Moustachos** [comment] 2016-12-03 20:00
Ref #5979
