### ISSUE TITLE
Enhancement Shaman - Chain Lightning

### ISSUE THREAD

**Issue by FixDruid** [Valhalla-Gaming/Tracker#7830] opened 2016-11-27 18:05 UTC
**Describe the issue you're having**:
Chain Lightning on enhancement shamans hits like 500 times
**Explain how you expect it work**:
Don't know. Just don't expect it to hit 50 times 200k damage.
**Steps to reproduce the problem**:

1. Cast Chain Lightning

Screenshot
http://imgur.com/a/QfS8e

**Comment by Zulbox** [comment] 2016-11-27 18:09
Same as your Coldrinn Fang.

**Comment by FixDruid** [comment] 2016-11-27 18:36
Yea it's already getting fixed ^^

**Comment by FixDruid** [comment] 2016-11-27 18:36
Hense 'fix druid'

**Comment by Moustachos** [comment] 2016-11-29 10:14
Does it only happen in PvP / specific conditions? Because my Chain Lightning deals normal damage.

Also, I assume you're talking about Elemental specialization? Enhancement shamans don't have Chain Lightning.

**Comment by MrNonameNo3** [comment] 2016-11-30 18:42
my assumütion is 
http://www.wowhead.com/spell=204357/ride-the-lightning

43 Honor Talent

**Comment by Moustachos** [comment] 2016-12-04 12:25
Thanks for the precision, it was indeed caused by Ride the Lightning and will be fixed on next update.

**Comment by Moustachos** [comment] 2016-12-04 12:25
Ref #5979

**Closed** 2016-12-04 12:25 UTC
Labels: Class-Shaman
