### ISSUE TITLE
Hunter change from 1 spec to another (survival to MM)

### ISSUE THREAD

**Issue by neloosefu** [Valhalla-Gaming/Tracker#1175] opened 2015-06-22 17:29 UTC
Ive just noticed that when ive change from survival to MM I don't get any focus loose when I cast spells or use skills

**Comment by Moustachos** [comment] 2016-05-12 15:05
Can't reproduce this bug, looks like a character-specific issue.

Closing it, please contact a GM.

**Comment by Moustachos** [comment] 2016-05-12 15:05
Ref #2266

**Closed by Moustachos** 2016-05-12 15:05 UTC
Labels: Class-Hunter, Priority-High
