### ISSUE TITLE
[Warlock] [Spell] [Demonology]

### ISSUE THREAD

**Issue by Turner12345** [Valhalla-Gaming/Tracker#7848] opened 2016-11-29 09:10 UTC
**Describe the issue you're having**:
The hand of gul'dan is not working properly
**Explain how you expect it work**:
When the spell drops the wild imps does not appear , it should spawn depending on how many shards you have but i tried many times no wild imps appear
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=105174/hand-of-guldan

**Comment by Moustachos** [comment] 2016-11-29 14:22
Duplicate of #6156

**Comment by Moustachos** [comment] 2016-11-29 14:22
Ref #6156

**Closed** 2016-11-29 14:22 UTC
