### ISSUE TITLE
Death Knight [Death Pact]

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#1958] opened 2015-08-14 04:57 UTC
http://www.wowhead.com/spell=48743/death-pact Death Pact only give 25% max HP heal and doesn't add the absorbtion.

**Comment by CorentinDodon** [comment] 2016-01-15 16:54
Death Pact give 50% HP heal but the problem is the absorption is activated first so 25% of the heal is use to destroy the absorption so there is only 25% heal.
The absorption should be activated after the 50% HP heal

**Comment by Moustachos** [comment] 2016-02-22 20:51
Fixed on next update.

**Comment by Moustachos** [comment] 2016-02-22 20:51
Ref #2266

**Closed by Moustachos** 2016-02-22 20:51 UTC
Labels: Class-Death Knight, Type-Spell
