### ISSUE TITLE
Focus-Energy Problem

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#3937] opened 2015-12-12 10:53 UTC
After using some finishing move (like Ferocious Bite, Savage Roar) above 50 energy (actually I'm not sure about that amount) next combo generator ability (like Shred, Rake) costs more than it should OR resource bar shows incorrect amount of energy OR something else. Doesn't happen all the time so I have no idea what's the cause of it. I've tested it in Firelands and on Stormwind's Training Dummies.
For example: Shred cost's 40 energy but even though I have that amount of energy and my Shred ability on my bar is not greyed out (should be usable) I can't use it. There's no error message like "out of range", "not enough energy", "you are facing the wrong way", nothing. So sometimes my Shred is usable only when I have 60-70 energy AND all that energy is consumed on use.
I think it was fixed before recent crash (like 12 hours ago), gameplay was smooth without any major problems. Now it's little annoying.

**Comment by Collector-Hellscream** [comment] 2015-12-22 14:53
Still have that issue. Tested it at Ashran dummies.

I've noticed that Ferocious Bite SOMETIMES doesn't consume as much energy as it should. For example using it at 70 energy should consume 50 energy but instead "sometimes" it consumes like 30ish and after that all combo generators cost more than they should.

I thought that Soul of the Forest talent ('Your finishing moves grant 4 Energy per combo point.') could be the cause of it but I tried with and without it with same result (relogged after changing talents). I often use that instant Healing Touch (from Predatory Swiftness) between my rotation so maybe there's some issue. Or maybe (detective mode activated) problem is with clearcasting. I have no idea now.

If someone could tell me the name of some recording program I would gladly throw a video of that issue here.

**Comment by Collector-Hellscream** [comment] 2015-12-22 15:28
I'll add here old topic from forum about it. It was fixed some time ago.

http://www.hellscream-wow.com/forum/viewtopic.php?f=8&t=2377

**Comment by EPS1L0N** [comment] 2015-12-23 01:27
> For example using it at 70 energy should consume 50 energy but instead "sometimes" it consumes like 30ish and after that all combo generators cost more than they should.

this is clearcasting im almost certain. clearcasting causes the cost of feroc to be free, but it still takes up to 25 for the bonus damage

**Comment by Collector-Hellscream** [comment] 2015-12-23 12:29
But I didn't saw in your video my issue. 
My combo generator abilities are useable, their icons are not greyed out or red or whatever. There's no error message when I hit the button with Shred for example. But when I hit it nothing happens even tho I have 40+ energy on my resource bar. And when I am finally able to use it, it takes all the energy - more than 40. 
And I'm 99% sure that after one of the updates feral gameplay was very smooth without that problem. When I had 40 energy I was able to actually use Shred at 40 energy. Did a lot of draenor world bosses with and without that issue. And I have no idea why you don't have it :(
Maybe that's because of some talent. I use at 15-feline swiftness, 30-ysera's gift, 45-typhoon, 60-soul of the forest. 75-mighty bash, 90-dream of cenarius, 100-claws of shirvallah.

**Comment by Collector-Hellscream** [comment] 2015-12-23 20:10
Ok, I just entered the game after recent update and... problem disappeared -.- What happened? ;d

**Comment by EPS1L0N** [comment] 2015-12-23 21:13
We did some power changes to fix shadow priest orbs that broke recently. That's probably it. I'll go ahead and close this now then

**Comment by Collector-Hellscream** [comment] 2015-12-23 23:00
Thank you :) Hope it won't come back ;P

**Comment by Collector-Hellscream** [comment] 2015-12-25 11:52
Issue returned after recent update.

**Comment by Collector-Hellscream** [comment] 2015-12-26 01:49
https://www.youtube.com/watch?v=o6sSwox9tZI
Here's video of my problem. Sadly it's still here with me. Hope it somehow helps.

There's already all informations about my character here and on forum topic: http://valhalla-realms.com/forum/viewtopic.php?f=8&t=2377

In video: first I use Shred multiple times then Ferocious Bite. Everything works perfectly. Then I use Shreds again and Tiger's Fury to speed up things. After next Ferocious Bite I'm trying to use Shred but can't and that is my problem. Next Shred is ok. Video ends.

Deleting cache helps only sometimes and not for long. Maybe there's something wrong with garrison phasing, Clearcasting, Ferocious Bite energy bonus, haste/energy regeneration or some talent. I have no idea but it's sometimes very frustrating. Especially in PvP combat and in raids with lots of buffs and some haste increase effects like bloodlust/time warp.

**Comment by Collector-Hellscream** [comment] 2015-12-27 13:28
Only thing I can add is that happenes only after Ferocious Bite that doesn't consume 'more energy to increase damage'. Just basic energy cost. And it's not necessarily Ferocious Bite used during Clearcasting.
Also it's rare when you're on your own and often when in party/raid with lots of buffs maybe.

**Comment by EPS1L0N** [comment] 2015-12-27 22:24
i think it's just a visual bug, im not sure why it happens though.

**Comment by Collector-Valhalla** [comment] 2016-05-04 00:18
There's a similar problem with hunter's focus bar. Sometimes (thankfully it's rare) abilities "cost" an additional 10 focus.

**Comment by Collector-Valhalla** [comment] 2016-05-10 13:00
Hunter's focus bar, ferals and ww monks energy bar (probably rogue too) they all share that problem.

**Comment by Collector-Valhalla** [comment] 2016-05-23 11:41
I have made new druid maybe a week ago or less. Same race, same account and he's without any energy problem. Everything works perfectly fine on him (at least for now, he's at lvl 91). But I have this problem on my old druid, pretty fresh monk (1 month old maybe) and hunter (also created 1 month ago).

**Closed** 2016-10-05 22:18 UTC
Labels: Class-Druid
