### ISSUE TITLE
warrior [execute] bug

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#4500] opened 2016-02-05 05:25 UTC
[execute] doesn't hit with off hand as fury warr http://www.wowhead.com/spell=140817/execute#modified-by
http://i.imgur.com/CUs6BPQ.jpg[/img]

**Comment by Nienz** [comment] 2016-02-05 09:31
Doesnt say anything about exectute with off hand wep, and for reference it works as intended

**Comment by Bombrick** [comment] 2016-02-05 16:01
No It isn't working as intended if you have a warrior turn to fury spec and you will see execute with off hand in the spell description

**Comment by Tregeta** [comment] 2016-02-21 18:01
@sandokana
Comment Quote Merged
> Execute spell for arms warrior spec deals ridiculously low dmg and does not consume extra rage to increase dmg up to a limit, which is huge for arms warriors.

**Comment by avandarkwalker** [comment] 2016-02-22 02:18
the prob is for fury it works for the main hand but not the ofhand, for arms doesn't work cuz mastery doesn't increase damge and the extra rage consume too



—

**Closed** 2016-03-09 20:32 UTC
Labels: Class-Warrior, Type-Spell

**Comment by Moustachos** [comment] 2016-03-09 20:34
Ref #2266
