### ISSUE TITLE
Mayla Highmountain Bug ?

### ISSUE THREAD

**Issue by MyJ3** [Valhalla-Gaming/Tracker#8255] opened 2016-12-25 22:46 UTC
Hola buenas estaba haciendo la cadena de misiones de monte alto y cuando completo esta misión http://www.wowhead.com/quest=38909/get-to-high-ground#comments en el npc http://www.wowhead.com/npc=97352/mayla-highmountain no me da la siguiente misión --> http://www.wowhead.com/quest=38912/the-bloodtotem-tribe. Esta el Npc Bug o que tengo que hacer?

Hello good I was doing the Mount High Missions Chain and when I completed this mission http://www.wowhead.com/quest=38909/get-to-high-ground#comments at npc http: //www.wowhead. Com / npc = 97352 / mayla-highmountain does not give me the following mission -> http://www.wowhead.com/quest=38912/the-bloodtotem-tribe. Is this the Npc Bug or do I have to do?

@Guybrush-VR

**Comment by Guybrush-VR** [comment] 2016-12-26 14:19
This is not a bug, I only scripted the two first chapters and one side quest-line. You won't be able to do what is after until I fix it! :-)
I'm closing it for now!

**Closed by Guybrush-VR** 2016-12-26 14:19 UTC
