### ISSUE TITLE
 [Shockwave] (Tank)

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#6850] opened 2016-09-23 17:05 UTC
**Describe the issue you're having**:
This spell when you learn it dissapear and the tanks can't use it.
**Explain how you expect it work**:
Sends a wave of force in a frontal cone, causing (47.5% of Attack power) damage and stunning all enemies within 10 yards for 4 sec.  Cooldown reduced by 20 sec if it strikes at least 3 targets.
**Steps to reproduce the problem**:

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=46968/shockwave

**Comment by Moustachos** [comment] 2017-01-03 15:45
Can't reproduce this issue, closing.

**Comment by Moustachos** [comment] 2017-01-03 15:45
Ref #5979

**Closed by Moustachos** 2017-01-03 15:45 UTC
