### ISSUE TITLE
Shaman Tidal Chains Trait

### ISSUE THREAD

**Issue by kpurc** [Valhalla-Gaming/Tracker#7573] opened 2016-11-07 23:32 UTC
**Describe the issue you're having**:
Tidal Chains passive does not add the correct amount of extra crit chance onto tidal waves. After getting the artifact trait to rank 3 the tidal waves passives (which also doesn't proc yet) states its 52% (gaining 4% for each rank in the artifact talent), total of a 12% gain on Tidal Waves crit chance.
**Explain how you expect it work**:
 It should be increase the crit chance of Todal wave by a total of 30% (10% each rank) when finished a total of 70% crit chance from Tidal Waves with rank 3 Tidal Chains
**Steps to reproduce the problem**:

1. Base Tidal waves is 40% in patch 7.0.3
2. Get rank 3 Tidal Chains
3. Notice the difference

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=53390/tidal-waves#changelog
http://www.wowhead.com/spell=207088/tidal-chains

**Comment by Redrian-Valhalla** [comment] 2016-11-08 13:53
https://github.com/Valhalla-Gaming/Tracker/issues/7207

**Comment by kpurc** [comment] 2016-11-08 15:08
This issue is not about Tidal Waves https://github.com/Valhalla-Gaming/Tracker/issues/7207, This issue is with the artifact trait that modifies Tidal Waves, I believe that regardless of how informative the other link is, it lacks that the trait is on the artifact tree is broken, which is what this issue is. I believe this should be reopened

**Comment by Redrian-Valhalla** [comment] 2016-11-08 23:47
You're right, my bad.

**Comment by kpurc** [comment] 2016-11-08 23:54
No worries!

**Comment by Moustachos** [comment] 2016-11-23 16:44
Not a bug, this talent is multiplicative, not additive.

Tidal Waves has a base effect of 30% (Healing Wave) / 40% (Healing Surge).

With rank 1 of Tidal Chains, each effect is multiplied by 1.1 (because each rank adds 10%), so the effect will be 33% on Healing Wave / 44% of Healing Surge and so on for higher ranks.

Closing the issue, this trait works just fine.

**Comment by Moustachos** [comment] 2016-11-23 16:44
Ref #5979

**Closed by Moustachos** 2016-11-23 16:44 UTC
Labels: Class-Shaman
