### ISSUE TITLE
Warrior Recklessness

### ISSUE THREAD

**Issue by sandokana** [Valhalla-Gaming/Tracker#4749] opened 2016-02-22 21:47 UTC
warrior ability Recklessness does not work at all.

**Comment by Moustachos** [comment] 2016-03-08 15:53
This spell works as intended.

The only bug with Recklessness is that it wasn't activating Battle Stance when used in Defensive Stance (as stated in the tooltip), it will be fixed on next update.

**Comment by Moustachos** [comment] 2016-03-08 15:54
Ref #2266

**Closed by Moustachos** 2016-03-08 15:53 UTC
Labels: Class-Warrior
