### ISSUE TITLE
capturing objectives with absorb effect

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4716] opened 2016-02-19 19:45 UTC
I don't know how it should work but I noticed that you can still capture bases/flags in battlegrounds while being attacked/damaged if you have some absorb effect on yourself like all those shields from protection warriors, brewmaster monks and discipline priests.

**Comment by Myrmidonx** [comment] 2016-02-19 20:16
someone already posted this but:

wow.gamepedia.com/Interrupt

absorb : resist any interrupt/pushback

**Comment by Collector-Valhalla** [comment] 2016-02-19 20:28
I can't see anything there about **pvp objectives** and I never played on retail so I'll look for answer now.

**Comment by Myrmidonx** [comment] 2016-02-19 21:56
well its like the same thing
a player start to cast -capture- in a -channeling- mechanic

if the player has enough absorb, player "B" cant interrupt, therefore u need to break the absorb buff

**Comment by Bombrick** [comment] 2016-02-21 13:44
No @Myrmidonx This isn't supposed to happen you can't cap while in shield Tried on retail (since long time not sure if changed)

**Comment by Myrmidonx** [comment] 2016-02-22 19:49
i already posted the interrupt page in this thread.

It explains the interrupt and absorb mechanics.

**Comment by Myrmidonx** [comment] 2016-02-22 22:25
well, i just pm a friend of mine playing the blizz server and the absorb resisting the interruption in BGs its RETAIL and working as intended (he even use the absorb trinket)


for me this issue its closed.

**Comment by Bombrick** [comment] 2016-02-23 20:30
Not closed yet People with Immune shields like palays can't Capture a flag

**Comment by Myrmidonx** [comment] 2016-02-23 21:57
bombrik
www.wowhead.com/spell=642/divine-shield

open another issue please, this is another skill with a different mechanic

**Comment by EPS1L0N** [comment] 2016-02-24 05:16
> well, i just pm a friend of mine playing the blizz server and the absorb resisting the interruption in BGs its RETAIL and working as intended (he even use the absorb trinket)

Direct damage should interrupt capturing, regardless of if you have a shield up. DoT's shouldn't

**Comment by Myrmidonx** [comment] 2016-02-24 15:55
we already have the discussion and the resolution, what this is all about?

are we on wotlk or BC?, this is WoD
blame the xpac, not the player

**Comment by Myrmidonx** [comment] 2016-02-24 17:35
it is me or the last comment was erased?

**Comment by Bombrick** [comment] 2016-03-06 16:01
By interruption I meant interrupting capturing flag not spells  your friend misunderstood it

**Comment by Tregeta** [comment] 2016-04-19 00:56
should be fixed in latest update.

**Closed by Tregeta** 2016-04-19 00:56 UTC
Labels: Priority-High, PVP

**Comment by Collector-Valhalla** [comment] 2016-04-21 16:23
Players still can capture pvp objecives with absorb effect on while being damaged.

**Comment by Collector-Valhalla** [comment] 2016-04-26 15:47
still not fixed after recent update
