### ISSUE TITLE
[Worgen][Druid] Movement stacking

### ISSUE THREAD

**Issue by CageValhalla** [Valhalla-Gaming/Tracker#5841] opened 2016-07-24 07:34 UTC
Darkflight doesn't stack up on Dash.

[http://www.wowhead.com/spell=68992/darkflight](url)
[http://www.wowhead.com/spell=1850/dash](url)

**Comment by nuhrii** [comment] 2016-07-25 04:49
Close this, i believe this is working as intended. In patch 6.0.2 movement bonuses that are temporary do not stack and only the one with the highest bonus will be applied
http://us.battle.net/wow/en/blog/15682579/the-iron-tide-602-patch-notes-10-13-2014#movement_speed

**Comment by Tregeta** [comment] 2016-07-25 16:31
After testing, these spells do not stack.

**Closed by Tregeta** 2016-07-25 16:31 UTC
Labels: Type-Script, Type-Spell
