### ISSUE TITLE
Chaos bolt

### ISSUE THREAD

**Issue by Redrian-Valhalla** [Valhalla-Gaming/Tracker#8167] opened 2016-12-16 17:51 UTC
**Describe the issue you're having**:
Chaos bolt deals too much damage, spamming it is enough to outperform any other dps spec in the game.
**Explain how you expect it work**:
It has to deal proper damage.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=116858/chaos-bolt

**Comment by Moustachos** [comment] 2016-12-20 07:57
As far as I can tell by quickly testing the spell, damage looks legit (keep in mind that it's affected by both mastery and critical strike chance).

Any specific circumstance / talent to pick to reproduce this issue?

**Comment by Redrian-Valhalla** [comment] 2016-12-20 09:00
No special circumstance, after talking to several warlocks, they confirmed th damage is.exaggeted so I decided to report this assiming nobody did because of convenience, being top damage by using the same ability in a loop sounts too imnatural to be normal, I've seen players killing Levantus just like that.

**Comment by Moustachos** [comment] 2016-12-20 21:35
Honestly I don't think there's anything wrong with this spell's damage, but it shouldn't be that much spammable, because at the moment you gain a soul shard on every tick of Immolate and it will be fixed on next update.

So I'm closing this report, feel free to open another once next update is live if you still think damage are too high (with proofs), but I don't think that's the case, Chaos Bolt is meant to be Destruction's most powerful spell.

**Comment by Moustachos** [comment] 2016-12-20 21:35
Ref #5979

**Closed by Moustachos** 2016-12-20 21:35 UTC
Labels: Class-Warlock
