### ISSUE TITLE
[VDH] Talents Fel Eruption/ Sigil of Chains

### ISSUE THREAD

**Issue by CageValhalla** [Valhalla-Gaming/Tracker#6309] opened 2016-09-07 22:08 UTC
Those two are mixed up in talent tree,where when u pick one u get other.

**Comment by Moustachos** [comment] 2016-10-01 21:36
Can't reproduce this issue on current version, closing.

**Comment by Moustachos** [comment] 2016-10-01 21:36
Ref #5979

**Closed by Moustachos** 2016-10-01 21:36 UTC
