### ISSUE TITLE
[Hunter] Infinite Focus 

### ISSUE THREAD

**Issue by lazardominik18** [Valhalla-Gaming/Tracker#5993] opened 2016-09-02 15:25 UTC
I didnt lose focus on anything.

**Comment by Trekex** [comment] 2016-09-02 15:26
Awesome :P

**Comment by Moustachos** [comment] 2016-10-06 14:52
Can't reproduce this issue on current version, closing.

**Comment by Moustachos** [comment] 2016-10-06 14:52
Ref #5979

**Closed by Moustachos** 2016-10-06 14:52 UTC
Labels: Class-Hunter
