### ISSUE TITLE
Tank specs dmg is bugged - Too big! Check screenshot

### ISSUE THREAD

**Issue by Psychadelic** [Valhalla-Gaming/Tracker#8456] opened 2017-01-15 22:16 UTC
**Describe the issue you're having**:

Tanks do more dmg then Dps ?

**Explain how you expect it work**:

That's absurd. Check out his Dmg compared to other players.....
![osmons dmh](https://cloud.githubusercontent.com/assets/24637106/21966692/f8e6550e-db80-11e6-970c-49a80f7c057b.jpg)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Psychadelic** [comment] 2017-01-15 22:16
The top guy is Tank spec...

**Comment by dalabug** [comment] 2017-01-16 00:04
Later that day ... http://i.imgur.com/Lh59L3z.jpg

You really "fixed" the warrior with the last patch.

**Comment by Hemoglobine-Valhalla** [comment] 2017-01-16 00:26
Well, Protection warrior have many aoe skills, which means if basically 5+ guys attack him and he do use revenge dealing 250k each, he will make 1.3m damage + bleed + thunderstorm + etc etc, basically damage isn't everything, same goes for brewmaster, mostly aoe damage, to a single target i do over 53k dps with my artifact at level 28 + 854 ilvl of the artifact + 820 of my gear, with 3 targets together i can do 148k - 160k dps easy, basically due aoe damage, if you were single target damage would be way less, what does this means? damage isn't everything and aoe damage does counts.

**Comment by Psychadelic** [comment] 2017-01-16 02:50
If you want to tell me that this is normal dmg for Tank specs... i would
advise you to delete wow.

**Comment by dalabug** [comment] 2017-01-16 06:08
Hey, if the a warrior can 2 shot kill anything < mail (revenge + shield slam ~ 700k) maybe they should fix the other classes to do the same. As a rogue I barely see crits at 120-130k.

**Comment by Hemoglobine-Valhalla** [comment] 2017-01-16 12:06
It is normal if the dps are currently grouping up to kill the same target, you won't do the same damage to 1 person being hitted versus 5 than 1 hitting 5, anyway since i don't wanna make an argument i will simple stop this drama, anyway the report doesn't even have a base, so it is pointless.

**Comment by Psychadelic** [comment] 2017-01-16 12:10
ofc its pointless since you are also abusing tank specs.. cant you just l2p
?

**Comment by neano300** [comment] 2017-01-16 13:34
It's funny, because the balance of the server sucks and you want a nerf now? huehue :D

**Comment by ixodan** [comment] 2017-01-16 13:49
first of all, psychadelic u shouldnt talk about dmg or bugs cus ur the most bugged class of the server so pls be quit . second, tanks are not bugged just missing pvp templates so ur issue is pointless thank you .

**Comment by Traveler-Valhalla** [comment] 2017-01-16 13:50
There's still lots of bugs on each class/spec. Some making class "too good" (imo rogue) and some making it just "garbage" (imo spriest). 
I guess that "too big tank damage" will be fixed with PvP templates. All tank specs in PvP have "[All damage done reduced by 25%](http://www.arenajunkies.com/topic/349054-pvp-stat-templates-and-spell-multipliers/)" plus some other spells/stats adjustments. And there's some dev [working on it](https://valhalla-realms.com/forum/viewtopic.php?f=41&t=8233) so we have to be patient and just wait.
With templates fixed there'll be a clearer view for any specific bugs etc.

**Comment by Psychadelic** [comment] 2017-01-16 20:14
Tank specs cant do more dmg then Dmg specs... thats ridicolous I hve been
in same bg with many tanks with bigger dmg then mine... when im almost
awlays in top 3 dps.

**Comment by neano300** [comment] 2017-01-17 12:52
Well I'am the top of every bg in every server when I play ^^,

**Comment by dalabug** [comment] 2017-01-17 20:47
This is your "fixed" warrior class:

![wow71](https://cloud.githubusercontent.com/assets/6592719/22039140/bfa334f6-dd06-11e6-922c-566a50b843b2.png)

**Comment by Hemoglobine-Valhalla** [comment] 2017-01-18 03:55
That's just numbers, with burst + right trinkets you can even hit more than that, don't forget about berseker from the bg which also increases damage done.

**Comment by Psychadelic** [comment] 2017-01-18 07:52
Dude you think we are all retarted or what ? I use berserker also all the
time and use mostly AOE's and those tanks do double dmg then mine! Where is
the logic in that?

**Comment by Guybrush-VR** [comment] 2017-01-18 09:51
There is not enough information to be able to zero in on the issue at hand here. It looks like it is mostly a lack of PvP Templates though. This aspect is being worked on so hopefully that should solve it. If you think that one spell in particular is not working as intended, please create a new issue with detailed informations.
I'm closing it now. :dancer:

**Closed by Guybrush-VR** 2017-01-18 09:51 UTC

**Comment by Psychadelic** [comment] 2017-01-18 10:28
PvP templates will reduce 25% of their dmg... That's not really going to
solve the problem.
