### ISSUE TITLE
warlock: soulwell

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6500] opened 2016-09-10 16:35 UTC
**Describe the issue you're having**:the soulwell does not give healthstone

**Explain how you expect it work**:party and raid members should be able to click the soulwell and be given a healthstone

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=29893/create-soulwell

**Comment by nuhrii** [comment] 2016-09-10 23:35
duplicate of #4872

**Comment by llamalama** [comment] 2016-10-13 22:03
Still not fixed, please reopen issue.

**Comment by Moustachos** [comment] 2016-12-04 02:52
Ref #5979

**Closed** 2016-12-04 02:51 UTC
