### ISSUE TITLE
Glyph Auction House Deposit Prices

### ISSUE THREAD

**Issue by VictorTyne** [Valhalla-Gaming/Tracker#5650] opened 2016-06-23 07:24 UTC
Some glyphs, when put up for sale on the auction house, have a deposit far greater than what is shown in the Auction House. Most glyphs show a deposit of 1s and end up charging you 3s, but some charge several gold just to put up.

Affected glyphs:

Glyph of Purification - 75s?
Soul Consumption
Glyph of Corpse Explosion - 1g 48s 
Glyph of Borrowed Time - 1g 50s
Glyph of Cleanse - >16g

**Comment by Luminescent-Valhalla** [comment] 2016-06-23 15:02
auction house deposits have already been reported #2387

**Comment by Tregeta** [comment] 2016-06-24 21:53
Duplicate of Neutral AH issue

**Closed by Tregeta** 2016-06-24 21:53 UTC
