### ISSUE TITLE
[Vendors] [Legacy Honor Quartermasters]

### ISSUE THREAD

**Issue by JozV** [Valhalla-Gaming/Tracker#7015] opened 2016-10-02 17:42 UTC
**Describe the issue you're having**:
Legacy honor quartermasters don't work.

**Explain how you expect it work**:
The quartermasters should sell legacy armor/weapons for, at least, gold.

**Steps to reproduce the problem**:

1. Go to any legacy honor quartermaster 
2. Attempt to buy an item

**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=YH7QjTrLbMk&feature=youtu.be

**Comment by Redrian-Valhalla** [comment] 2016-10-02 17:47
Duplicate of https://github.com/Valhalla-Gaming/Tracker/issues/6289

**Closed by Redrian-Valhalla** 2016-10-02 17:47 UTC
