### ISSUE TITLE
Paladin : Game Breaking Shield of Righteousness

### ISSUE THREAD

**Issue by kpurc** [Valhalla-Gaming/Tracker#7907] opened 2016-12-01 21:41 UTC
**Describe the issue you're having**:
It kills everything, INSTANTLY
**Explain how you expect it work**:
It shouldnt! Mitigate the dmg, Monk was mitigated, this is too game breaking
**Steps to reproduce the problem**:

1.
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://imgur.com/a/Beara

**Comment by Moustachos** [comment] 2016-12-03 09:41
Just checked the spell and it works as intended, this screenshot doesn't reflect the average damage of Shield of the Righteous because:
- Bloodshade has Berserking BG buff (+30% damage)
- you are in his Consecration (+20% Shield of the Righteous damage)

And this doesn't include the other buffs he had, plus the potential debuffs you had on you by the time you died.

Closing.

**Comment by Moustachos** [comment] 2016-12-03 09:41
Ref #5979

**Closed by Moustachos** 2016-12-03 09:41 UTC
Labels: Class-Paladin, Priority-High

**Comment by kpurc** [comment] 2016-12-03 10:20
I don't care about that, I do  understand those circumstances, I'm clearly
stating out side of berserker buff people are still one shotting with this
skill, the damage is too large regardless. This screenshot was only a mere
example of the numbers that can be perfomed. This spell flacid hits almost
twice as much as a monks artifact ability. I don't believe it is accurate
for a protection paladin to out dps everyone in the battleground or out in
the world farming by solely pushing 3-4 buttons. Their dps is immense
compared to other specs. For example, out in the world soloing a single
large health mob, the prot pala would do 160k dps, the monk 110k, and the
mage/any other dps 80-90k. read that how you will but something is doing
too much damage or the others are doing too little.


On Dec 3, 2016 4:41 AM, "Moustachos" <notifications@github.com> wrote:

Ref #5979 <https://github.com/Valhalla-Gaming/Tracker/issues/5979>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Valhalla-Gaming/Tracker/issues/7907#issuecomment-264628926>,
or mute the thread

**Comment by kpurc** [comment] 2016-12-03 12:58
Statement from the person recieving the damage:
"
1 he kill me in 2 or 3 sec
2 i was im tank from have like 50% damange redoction
i mean im tank i was in bear form
to be exact i have 43.71
% demange redoction
3-- i have  [Barkskin] [Ironfur] [Survival Instincts] that i use whem im geting to much dps, if pala can do that to a tank what can he do to rest of people
"

**Comment by Moustachos** [comment] 2016-12-03 20:24
Shield of the Righteous isn't affected by armor.

So unless this player was using some kind of glitch, I see no issue with this spell so far.
