### ISSUE TITLE
Calling Pet Hunter Ability corrupt

### ISSUE THREAD

**Issue by Vofuse** [Valhalla-Gaming/Tracker#4957] opened 2016-03-12 10:07 UTC
I made a blood elf hunter and when i entered again the the realm my pet dissapeared. When i press the call button in the hotbar seems stuck and the one from spell book doesn't make anything after the calling animation is made.

**Comment by Moustachos** [comment] 2016-05-12 15:02
Can't reproduce this bug, looks like a character-specific issue.

Closing it, please contact a GM.

**Comment by Moustachos** [comment] 2016-05-12 15:03
Ref #2266

**Closed by Moustachos** 2016-05-12 15:02 UTC
Labels: Class-Hunter, Type-Pet
