### ISSUE TITLE
Hunter: Scalehides, probably Oxen and Mechanicals

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#6330] opened 2016-09-07 23:31 UTC
Can't Tame any memebers of the new Scalehide family and probably Oxen and Mechanical familes

**Comment by Moustachos** [comment] 2016-10-10 16:20
Can't reproduce this issue, I've been able to tame the following Scalehide pets:
- http://www.wowhead.com/npc=56239/adolescent-mushan
- http://www.wowhead.com/npc=4700/aged-kodo

If you're unable to tame a specific creature, please provide a wowhead link, closing the issue.

**Comment by Moustachos** [comment] 2016-10-10 16:20
Ref #5979

**Closed by Moustachos** 2016-10-10 16:20 UTC
