### ISSUE TITLE
trash (guardian druid)

### ISSUE THREAD

**Issue by aetoni** [Valhalla-Gaming/Tracker#7001] opened 2016-09-30 20:42 UTC
**Describe the issue you're having**: trash abillity does no overtime damage like it should nor does it stack

**Explain how you expect it work**: it should deal damage then apply overtime wich can stack up to 3 times

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
![screenshot_1](https://cloud.githubusercontent.com/assets/22433174/19006310/bbf4fe3c-8713-11e6-83ad-5de47f11729d.png)

**Comment by Redrian-Valhalla** [comment] 2016-09-30 21:23
Duplicate of https://github.com/Valhalla-Gaming/Tracker/issues/6428

**Closed by Redrian-Valhalla** 2016-09-30 21:23 UTC
