### ISSUE TITLE
warlock: rain of fire

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6499] opened 2016-09-10 16:33 UTC
**Describe the issue you're having**: rain of fire is not doing any damage

**Explain how you expect it work**:rain of fire is suppose to to an amount of damage to each target in the targeted area over a period of time

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=5740/rain-of-fire

**Comment by nuhrii** [comment] 2016-09-10 23:32
duplicate of #2573

**Closed** 2016-09-13 17:30 UTC

**Comment by Moustachos** [comment] 2016-12-20 22:44
Ref #5979
