### ISSUE TITLE
Warlock: cataclysm

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6489] opened 2016-09-10 15:43 UTC
**Describe the issue you're having**: the talented spell cataclysm is not applying immolate to targets it hits
**Explain how you expect it work**:
catatclysm is suppose to apply immolate to all targets hit
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=152108/cataclysm

**Comment by nuhrii** [comment] 2016-09-10 23:30
close this, duplicate of  #5625

**Closed** 2016-12-20 22:43 UTC

**Comment by Moustachos** [comment] 2016-12-20 22:45
Ref #5979
