### ISSUE TITLE
[Warlock] Back Draft stacking makes Chaos Bolt lethal

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#8693] opened 2017-02-04 16:24 UTC
**Describe the issue you're having**:
Backdraft talent stacks making chaos bolt super effective.

**Explain how you expect it work**:
Should not stack like this
**Links to Wowhead, YouTube, etc**:
http://imgur.com/XQsX9uz
http://imgur.com/nYjkJOE

**Comment by Analog-Valhalla** [comment] 2017-02-04 16:27
https://valhalla-realms.com/forum/viewtopic.php?f=10&t=8489

**Comment by shadowend** [comment] 2017-02-04 22:31
The problem is not with chaos bolt dmg its normal the proplem is with Back Draft talent when it stacks it allows u to cast 2 insta chaos bolts each with 600-800 k thats the problem 

Note: Chaos bolts can deal upto 1.5 mill in this patch when full buffed and have high gear .

https://www.youtube.com/watch?v=rI0CGpkzWmw

**Comment by Moustachos** [comment] 2017-02-05 11:12
Will be fixed on next update.

**Closed by Moustachos** 2017-02-05 11:12 UTC
Labels: Class-Warlock, Priority-High, Type-Spell
