### ISSUE TITLE
Kurenai Reputation Granted Too Low

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#5433] opened 2016-05-23 15:33 UTC
Having completed the Nagrand quests and the Zangarmarsh too - except for the one or two that doesn't work, should put me at almost Revered. I have just hit Honored.
Most of the quests should give much more than 250 reputation.
The last one I checked for sure was Cho'War the Pillager which granted only 250 Kurenai reputation and should have granted 700.
Please check this list and update the amount of reputation granted so that grinding for a Talbuk mount is not more painful than it already is.
Link: http://wowwiki.wikia.com/wiki/Kurenai_Reputation_Guide

**Comment by Trekex** [comment] 2016-05-24 16:32
That list may be outdated. Wowhead shows a different amount. (Anyway that quest you named shows 350 on wowhead so it's wrong in both cases)

**Comment by Tregeta** [comment] 2016-05-24 19:19
The comments state that it has been increased since 3.3.5, notably watching Gitgudguide's video confirmed the increase, as such will be fixed in the next update.

**Closed by Tregeta** 2016-05-24 19:19 UTC
Labels: Type-Creature, Type-Quest, Type-Script
